### PR TITLE
Homepage Redesign and Major Documentation Upgrades

### PR DESCRIPTION
**Pull request by BluWizard10**
This is going to be something extra special... The goal I am doing is to make it so that there isn't a need to join the Discord Server to get an answer. For that, I'm implementing a lot of new Images, Videos, and Information so that the Documentation is as useful as it can be.

Since the size of this PR is so massive, I highly suggest you look over the deployment preview before merging this PR.

Let's get started with some of the changes so far...

### New
- Revamped the Home Page! Lots of layout adjustments. It is now on a dedicated `src/pages/index.md` page, which indicates to Docusaurus as the Home Page.
- Moved information about how to Download and Install Poiyomi Shaders into it's own dedicated Page in `download/download.md`. It includes information on both methods of install, such as the Manual Unity Package or using the VCC Repo.
- Redirects added in favor of the the new Download and Install Page.
- Added `robots.txt` for SEO indexing.
- Added Blog Post written by me, talking about all of these changes I'm making.
- Added `general/ui-language.md`.
- Added `credits.md` listing the contributors to the Docs. Credit where it's due!
- Added MANY new Images and Videos to the `Shading` category. Most of which are found in the `shading/main.md` page. I have done my best to present the various functions of these Lighting Types for better visual explanation.
- Added `shading/anisotropics.md`.
- Added `general/faq.md` which reflects a lot of frequently asked questions from the Discord Server.
- Added FontAwesome and Iconify Webfonts.
- Added Footer to the website.
- Added various `index.md` files in most of the Docs Categories.
- Added `general/special-versions.md` which documents the various different versions included in Poiyomi Shaders.

### Changes
- Replaced existing images on `shading/rim-lighting.md` in favor of the new Videos I've made.
- Changed header image and video on `outlines/outlines.md`.
- Reorganized the Thry Editor Category. Renamed "End User" to "Overview" instead. File name is still the same.
- Revamped the `special-fx/dissolve.md` Documentation with new Videos and better organization.
- Moved and added new sub-pages to Thry Editor category for some of the bigger features used in ThryEditor.
- Introduced keywords and description on all pages for SEO.
- Light and Dark Themes will now automatically match the client's theme by default.
- **Upgraded Docusaurus to v3.3.2.**

### Fixes
- More typos resolved, alongside re-adding some missing info I've caught.
- Fixed various links and arguments that broke or threw warnings during the Docusaurus v3 upgrade.

### Removed
- Removed `src/pages/poiyomitoonvcc.js` and added a redirect in favor of the new `download/download.md` page.

### CODE REVIEW

**Comment by BluWizard10** [comment]
All done! I've finished up everything I wanted to edit and resolved many nit-picky items I've noticed.

Ready for Review!

**Comment by slord399** [comment]
According to @Thryrallo following page seems not correct.
https://poidocs-git-fork-bluwizard10-blu-9-poi.vercel.app/thryeditor/cross-shader-editor#prerequisites

**Comment by BluWizard10** [comment]
> According to @Thryrallo following page seems not correct.
> 
> https://poidocs-git-fork-bluwizard10-blu-9-poi.vercel.app/thryeditor/cross-shader-editor#prerequisites

I see. What piece of information should I correct?

**Comment by ScruffyRules** [comment]
The Cross Shader Editor should allow any Poiyomi Variant or version to work at once

**Comment by BluWizard10** [comment]
> The Cross Shader Editor should allow any Poiyomi Variant or version to work at once

Gotcha. Last I checked, it wasn't able to. I assumed it was intentional.

**Comment by BluWizard10** [comment]
Fixed. Thanks for pointing it out. @slord399 @ScruffyRules

**Pull request merged**
